"""Estrutura inicial

Revision ID: 6cfd5444b137
Revises: 
Create Date: 2026-08-13 09:53:13.696490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cfd5444b137'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('administrador', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario'),
    schema='tele'
    )
    op.create_table('avisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_inativacao', sa.DateTime(), nullable=True),
    sa.Column('usuario_inativacao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['tele.usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_inativacao'], ['tele.usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tele'
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('acao', sa.String(length=300), nullable=True),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('detalhes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['tele.usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tele'
    )
    op.create_table('relatorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('turno', sa.String(length=1), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['tele.usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tele'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relatorios', schema='tele')
    op.drop_table('logs', schema='tele')
    op.drop_table('avisos', schema='tele')
    op.drop_table('usuarios', schema='tele')
    # ### end Alembic commands ###
